packages = ["pandas", "scikit-learn"]
[[fetch]]
from = 'https://raw.githubusercontent.com/LakshmanKishore/loanPrediction/main/model.pkl'
from = 'https://raw.githubusercontent.com/sahiltambe/Academic-Achievement-Analyzer/main/model.pkl'
from = 'https://github.com/sahiltambe/Academic-Achievement-Analyzer/main/model.pkl'
from = 'https://raw.githubusercontent.com/sahiltambe/Academic-Achievement-Analyzer/notebook/main/model.pkl'
from = 'https://raw.githubusercontent.com/sahiltambe/Academic-Achievement-Analyzer/notebook/main/model.pkl'
name = "Academic-Achievement-Analyzer"