packages = ["pandas", "scikit-learn"]

from = ['https://raw.githubusercontent.com/sahiltambe/Academic-Achievement-Analyzer/main/model.pkl', 'https://github.com/sahiltambe/Academic-Achievement-Analyzer/main/model.pkl']
name = "Academic-Achievement-Analyzer"
