packages = ["pandas", "scikit-learn", "numpy", "scipy", "clapack", "joblib", "distutils"]

from = ['https://raw.githubusercontent.com/sahiltambe/Academic-Achievement-Analyzer/main/model.pkl']

name = "Academic-Achievement-Analyzer"
